version: "3.7"

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: jobscheduler-kafka-1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes

  yugabyte:
    image: yugabytedb/yugabyte:latest
    container_name: jobscheduler-yugabyte-1
    command: ["/home/yugabyte/bin/yugabyted", "start", "--base_dir=/tmp/yb_data", "--daemon=false"]
    ports:
      - "5433:5433"   # YSQL (PostgreSQL)
      - "9042:9042"   # YCQL
      - "7000:7000"   # Web UI

  minio:
    image: minio/minio
    container_name: jobscheduler-minio-1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
